import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';import {mkdtempSync,rmSync} from 'node:fs';import path from 'node:path';import {chromium} from '@playwright/test';
const root=process.cwd(),work=path.resolve(root,'../../work'),temp=mkdtempSync(path.join(work,'town-test-')),port=18909;
const server=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:String(port),PROFILE_FILE:path.join(temp,'profiles.json'),PUBLIC_ORIGIN:''},windowsHide:true,stdio:['ignore','pipe','pipe']});let browser;
try{
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',c=>reject(Error(`server ${c}`)))});
 browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];
 async function enter(){const p=await(await browser.newContext({viewport:{width:1440,height:900}})).newPage();p.on('websocket',ws=>ws.on('framereceived',({payload})=>{const m=JSON.parse(payload);if(m.type==='town-state')p.town=m.players;if(m.type==='hello')p.pid=m.id;}));p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});await p.goto(`http://localhost:${port}`);await p.locator('#appearance-skip').click();await p.locator('#career-open:not([disabled])').waitFor();return p;}
 const a=await enter(),b=await enter();let town,peer; a.on('websocket',()=>{});
 const until=async fn=>{const start=Date.now();while(!await fn()){if(Date.now()-start>12000)throw Error('town timeout');await a.waitForTimeout(60)}};
 await a.click('#town-open');await b.click('#town-open');await until(async()=> (await a.locator('#town-count').innerText()).includes('2 人'));
 await a.locator('#town-canvas').focus();await a.keyboard.down('d');await a.waitForTimeout(2150);await a.keyboard.up('d');await a.keyboard.down('w');await a.waitForTimeout(1350);await a.keyboard.up('w');await until(()=>a.locator('#town-interact').isEnabled());assert((await a.locator('#town-interact').innerText()).includes('装扮工坊'));
 await until(()=>b.town?.some(p=>p.id===a.pid&&p.x>900&&p.y<410));
 await a.fill('#town-chat-input','小镇同步测试');await a.locator('#town-chat-form button').click();await until(async()=> (await b.locator('#town-chat').innerText()).includes('小镇同步测试'));
 await a.click('#town-wave');await a.screenshot({path:path.join(work,'town-desktop.png'),fullPage:true});await a.click('#town-interact');await a.locator('#career-dialog').waitFor({state:'visible'});await until(async()=> (await b.locator('#town-count').innerText()).includes('1 人'));
 await a.click('#close-career');await a.locator('#town-dialog').waitFor({state:'visible'});await a.setViewportSize({width:390,height:844});await a.screenshot({path:path.join(work,'town-mobile.png'),fullPage:true});assert.equal(await a.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await a.click('#close-town');await a.setViewportSize({width:1440,height:900});
 await b.click('#close-town');await b.click('#rooms-open');await b.selectOption('#room-create-mode','boss');await b.click('#room-create-button');await b.locator('#room-panel').waitFor({state:'visible'});
 await a.click('#rooms-open');await until(async()=>await a.locator('.public-room').count()===1);assert((await a.locator('.public-room').innerText()).includes('首领挑战'));await a.click('[data-room-filter=classic]');assert.equal(await a.locator('.public-room').count(),0);await a.click('[data-room-filter=all]');assert.equal(await a.locator('.public-room').count(),1);await a.screenshot({path:path.join(work,'game-lobby.png'),fullPage:true});await a.locator('.public-room button').click();await a.locator('#room-panel').waitFor({state:'visible'});await a.click('#leave-lobby');await a.locator('#home-panel').waitFor({state:'visible'});
 for(const mode of ['bio','survivor']){await a.click(`[data-ruleset=${mode}]`);await a.click('#ai-play');await a.locator('#survivor-picks').waitFor({state:'visible'});for(const viewport of [{width:1440,height:900},{width:390,height:844}]){await a.setViewportSize(viewport);const box=await a.locator('#survivor-picks').boundingBox();assert(box.height<=viewport.height*.59);assert(box.width<=viewport.width-39);assert(await a.locator('#game').isVisible());assert(await a.locator('#survivor-picks').evaluate(e=>getComputedStyle(e).backgroundColor.startsWith('rgba')));await a.screenshot({path:path.join(work,`${mode}-compact-${viewport.width}.png`),fullPage:true});}await a.locator('.survivor-card').first().click();await a.waitForTimeout(250);if(await a.locator('#survivor-picks').isVisible())await a.click('#survivor-pick-leave');else{await a.click('#fullscreen-button');assert(await a.evaluate(()=>document.fullscreenElement===document.documentElement));await a.click('#fullscreen-button');await a.click('#leave-game');}await a.locator('#home-panel').waitFor({state:'visible'});await a.setViewportSize({width:1440,height:900});}
 assert.deepEqual(errors,[]);console.log('PASS: two-client town presence, movement, proximity interaction, chat, page return, mobile layout; lobby filter and join; compact bio/survivor panels on desktop/mobile');
}finally{await browser?.close();server.kill();if(server.exitCode===null)await new Promise(resolve=>server.once('exit',resolve));rmSync(temp,{recursive:true,force:true});}
